name: DavidMDavis
favicon: null
layout_spectrum: 0.673545946367085
typography_spectrum: 0.1245060870423913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8564877733588219
  lightness: 0.2934652855619788
  saturation: 0.2659147912636399
  rhythmicContrast: 0.25158218340948224
purpose: []
